name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2      
    - name: Fetch tags for GitVersion
      run: git fetch --prune --tags --unshallow
    - name: Fetch master for GitVersion
      if: github.ref != 'refs/heads/main'
      run: git branch --create-reflog main origin/main
    - name: Run GitVersion
      id: gitversion
      uses: roryprimrose/rungitversion@v1.1.0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/Cake.Prompt.sln
    - name: Build
      run: dotnet build --no-restore -p:Version=${{ steps.gitversion.outputs.NuGetVersionV2 }} src/Cake.Prompt.sln
    - name: Test
      run: dotnet test --no-build --verbosity:normal src/Cake.Prompt.sln
    - name: Pack
      run: dotnet pack --no-build --verbosity:normal -p:Version=${{ steps.gitversion.outputs.NuGetVersionV2 }} src/Cake.Prompt/Cake.Prompt.csproj
    - name: Push
      run: dotnet nuget push ./src/Cake.Prompt/nupkg/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
